### ISSUE TITLE
Not woking with Apache 2.2 and PHP-FPM

### ISSUE THREAD

**Issue by farconada** [FriendsOfSymfony/FOSOAuthServerBundle#140]
the header Authorization Bearer is not recognized with Apache 2.2 + PHP-FPM even with
FastCGIExternalServer /var/www/fastcgi/php5.fcgi -socket /var/run/php-www.socket -idle-timeout 300 -pass-header HTTP_AUTHORIZATION -pass-header Authorization
and
RewriteCond %{HTTP:Authorization} ^(.+)$
RewriteRule .\* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

**Comment by choonge** [comment]
Running into this same problem right now. Did you ever manage to find a solution, @farconada ?

**Comment by choonge** [comment]
We figured it out - the bundle also attempts to read the access token from the request parameter named 'access_token', in OAuth2::getBearerTokenFromQuery(). So you can add this rewrite rule to add your token as a request parameter:

```
    RewriteCond %{HTTP:Authorization} ^(Bearer\ )(.*)$ [NC]
    RewriteRule ^(.*) $1?access_token=%2 [QSA]
```

Since it's an internal redirect, the token won't show up in your access logs either.
