### ISSUE TITLE
Integration with FOSUserBundle and FR3DLdapBundle

### ISSUE THREAD

**Issue by ordiovince** [FriendsOfSymfony/FOSOAuthServerBundle#181]
On our application we want to user those 3 bundles together but we have some problems.
The OAuth grant type is "resource owner password credentials".

With the login form everything is working properly, the password is checked with the LDAP and if the user doesn't exist, it's created on the database.

But when it comes to the OAtuh authentication:
- with "fos_user.user_provider.username" as user_provider:
  - if the user exists in the database, the bundle tries to check the password stored in the database but we do not save the password (checking with the LDAP) so it fails
  - if the user doesn't exist, the bundle doesn't find it and that's all
- with "fr3d_ldap.security.user.provider" as user_provider the user is found in the LDAP but the password is not retrieved from LDAP and the user is not created in the database

For us the solution is to enchain the providers like it is done with the chain_provider on security.providers.chain_providers.

Thank you in advance.

**Comment by BigBazooka007** [comment]
Hi. Could you please explain how you managed to get it to work with authorizoation code? Im struggling with the same problem. My frontend is in JS and its using grant_type= password to authorize user. All works fine, but when trying to get ldap users i got error because theres no password. 
When im using standard symfony form (/fos/login) all works fine. Ldap user is being downloaded, and authorized properly.. Any idea what am i doing wrong?

**Comment by ordiovince** [comment]
Hi, It was 3 years ago, a lot must have changed and I never worked with Symfony after that so I am afraid that it will be hard for me to help you. Maybe you can have more chance with someone from the community... (@willdurand)

Good luck anyway!
