### ISSUE TITLE
[Question] Problem with Refresh Token 

### ISSUE THREAD

**Issue by jaigm** [FriendsOfSymfony/FOSOAuthServerBundle#289]
Hi everyone:

I have a problem, in my pc, the refresh token works and its returned on the get params in the redirect uri, exactly how must to works, but in another server, i can't get the refresh tokens... i don't know why, it's the same code, the only difference can be the camel case sensitive of the SO (windows and linux). Thank you a lot and for this wonderful bundle :+1:

See ya, sorry for the tarzan's english language

**Comment by dtraore** [comment]
so @Spomky  if we don't need a refresh token to get a new access token how does it work to access_token.
Thx

**Comment by Spomky** [comment]
@dtraore excuse me but I am not sure to clearly understand what you are looking for.

To get a new access token using Client Credentials grant type, you just have to send a request with your confidential client (see [RFC6749#section-4.4.2](https://tools.ietf.org/html/rfc6749#section-4.4.2)). A refresh token is useless with this flow as it only requires a request from an authenticated confidential client:

```
 POST /token HTTP/1.1
 Host: server.example.com
 Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
 Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
```

Same goes for Implicit Grant Type, but the resource owner must authorize your client (see [RFC6749#section-4.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.1)).
IMHO, refresh tokens are forbidden because this flow is dedicated to public clients and such clients are incapable of maintaining the confidentiality of their credentials (stolen refresh tokens can be use to get access tokens and impersonate a client).

```
GET /authorize?response_type=token&client_id=s6BhdRkqt3&state=xyz&redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb HTTP/1.1
Host: server.example.com
```

**Comment by liuwenchao** [comment]
@Spomky Can I conclude that 'refresh token' is not supported anymore?

**Comment by Spomky** [comment]
@liuwenchao : No, refresh tokens are still supported and can be used with other flows

**Comment by liuwenchao** [comment]
Thanks, I figured *Not every access token will come with refresh token*, this was my major misunderstanding:

[Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1) Access token with optional Refresh token
[Implicit Grant](https://tools.ietf.org/html/rfc6749#section-4.1) Access token only
[Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.1) Access token with optional Refresh token
[Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.1) Access token only

Hope this is helpful to others.

**Comment by Spomky** [comment]
That's it!
