### ISSUE TITLE
Enable to specify user_checker in firewall settings

### ISSUE THREAD

**Issue by GSokol** [FriendsOfSymfony/FOSOAuthServerBundle#478]
In current realization the only symfony's system `security.user_checker` is provided to `OS\OAuthServerBundle\Security\Authentication\Provider\OAuthProvider`'s container. It's rather trickiy to inject there the custom one for the certain firewall area.

**Comment by denisWetexx** [comment]
Is there any concern in making the fix public?
I had the same problem trying to use the user_checker as proposed in https://symfony.com/doc/current/security/user_checkers.html
The configured user_checker does not get injected. Instead the default user checker is used 
in vendor/friendsofsymfony/oauth-server-bundle/Security/Authentication/Provider/OAuthProvider.php
so checking for disabled users is not possible without the fix for non AdvancedUserInterfaces or more custom authorization checks

**Comment by deguif** [comment]
It's now supported in master branch, see #660
